name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Add target for Linux
      run: rustup target add x86_64-unknown-linux-musl
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --target=x86_64-unknown-linux-musl --features ladder
